// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fast (
        p_src_mat_rows_read,
        p_src_mat_cols_read,
        p_src_mat_data_V_dout,
        p_src_mat_data_V_empty_n,
        p_src_mat_data_V_read,
        p_dst_mat_rows_read,
        p_dst_mat_cols_read,
        p_dst_mat_data_V_din,
        p_dst_mat_data_V_full_n,
        p_dst_mat_data_V_write,
        p_threshold,
        ap_clk,
        ap_rst,
        p_src_mat_rows_read_ap_vld,
        p_src_mat_cols_read_ap_vld,
        p_dst_mat_rows_read_ap_vld,
        p_dst_mat_cols_read_ap_vld,
        p_threshold_ap_vld,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] p_src_mat_rows_read;
input  [31:0] p_src_mat_cols_read;
input  [7:0] p_src_mat_data_V_dout;
input   p_src_mat_data_V_empty_n;
output   p_src_mat_data_V_read;
input  [31:0] p_dst_mat_rows_read;
input  [31:0] p_dst_mat_cols_read;
output  [7:0] p_dst_mat_data_V_din;
input   p_dst_mat_data_V_full_n;
output   p_dst_mat_data_V_write;
input  [7:0] p_threshold;
input   ap_clk;
input   ap_rst;
input   p_src_mat_rows_read_ap_vld;
input   p_src_mat_cols_read_ap_vld;
input   p_dst_mat_rows_read_ap_vld;
input   p_dst_mat_cols_read_ap_vld;
input   p_threshold_ap_vld;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    fast_Loop_1_proc5765_U0_ap_start;
wire    fast_Loop_1_proc5765_U0_start_full_n;
wire    fast_Loop_1_proc5765_U0_ap_done;
wire    fast_Loop_1_proc5765_U0_ap_continue;
wire    fast_Loop_1_proc5765_U0_ap_idle;
wire    fast_Loop_1_proc5765_U0_ap_ready;
wire    fast_Loop_1_proc5765_U0_start_out;
wire    fast_Loop_1_proc5765_U0_start_write;
wire    fast_Loop_1_proc5765_U0_p_src_mat_data_V_read;
wire   [7:0] fast_Loop_1_proc5765_U0_p_src_V_V_din;
wire    fast_Loop_1_proc5765_U0_p_src_V_V_write;
wire   [31:0] fast_Loop_1_proc5765_U0_p_src_mat_rows_read_out_din;
wire    fast_Loop_1_proc5765_U0_p_src_mat_rows_read_out_write;
wire   [31:0] fast_Loop_1_proc5765_U0_p_src_mat_cols_read_out_din;
wire    fast_Loop_1_proc5765_U0_p_src_mat_cols_read_out_write;
wire   [31:0] fast_Loop_1_proc5765_U0_p_dst_mat_rows_read_out_din;
wire    fast_Loop_1_proc5765_U0_p_dst_mat_rows_read_out_write;
wire   [31:0] fast_Loop_1_proc5765_U0_p_dst_mat_cols_read_out_din;
wire    fast_Loop_1_proc5765_U0_p_dst_mat_cols_read_out_write;
wire   [7:0] fast_Loop_1_proc5765_U0_p_threshold_out_din;
wire    fast_Loop_1_proc5765_U0_p_threshold_out_write;
wire    xFFastCornerDetectio_U0_p_strm_in_V_V_read;
wire   [7:0] xFFastCornerDetectio_U0_p_strm_out_V_V_din;
wire    xFFastCornerDetectio_U0_p_strm_out_V_V_write;
wire    xFFastCornerDetectio_U0_p_src_mat_rows_read_read;
wire    xFFastCornerDetectio_U0_p_src_mat_cols_read_read;
wire    xFFastCornerDetectio_U0_p_threshold_read;
wire    xFFastCornerDetectio_U0_ap_done;
wire    xFFastCornerDetectio_U0_ap_start;
wire    xFFastCornerDetectio_U0_ap_ready;
wire    xFFastCornerDetectio_U0_ap_idle;
wire    xFFastCornerDetectio_U0_ap_continue;
wire    fast_Loop_2_proc58_U0_ap_start;
wire    fast_Loop_2_proc58_U0_ap_done;
wire    fast_Loop_2_proc58_U0_ap_continue;
wire    fast_Loop_2_proc58_U0_ap_idle;
wire    fast_Loop_2_proc58_U0_ap_ready;
wire    fast_Loop_2_proc58_U0_p_dst_mat_rows_read_read;
wire    fast_Loop_2_proc58_U0_p_dst_mat_cols_read_read;
wire    fast_Loop_2_proc58_U0_p_dst_V_V_read;
wire   [7:0] fast_Loop_2_proc58_U0_p_dst_mat_data_V_din;
wire    fast_Loop_2_proc58_U0_p_dst_mat_data_V_write;
wire    ap_sync_continue;
wire    p_src_V_V_full_n;
wire   [7:0] p_src_V_V_dout;
wire    p_src_V_V_empty_n;
wire    p_src_mat_rows_read_c_full_n;
wire   [31:0] p_src_mat_rows_read_c_dout;
wire    p_src_mat_rows_read_c_empty_n;
wire    p_src_mat_cols_read_c_full_n;
wire   [31:0] p_src_mat_cols_read_c_dout;
wire    p_src_mat_cols_read_c_empty_n;
wire    p_dst_mat_rows_read_c_full_n;
wire   [31:0] p_dst_mat_rows_read_c_dout;
wire    p_dst_mat_rows_read_c_empty_n;
wire    p_dst_mat_cols_read_c_full_n;
wire   [31:0] p_dst_mat_cols_read_c_dout;
wire    p_dst_mat_cols_read_c_empty_n;
wire    p_threshold_c_full_n;
wire   [7:0] p_threshold_c_dout;
wire    p_threshold_c_empty_n;
wire    p_dst_V_V_full_n;
wire   [7:0] p_dst_V_V_dout;
wire    p_dst_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_xFFastCornerDetectio_U0_din;
wire    start_for_xFFastCornerDetectio_U0_full_n;
wire   [0:0] start_for_xFFastCornerDetectio_U0_dout;
wire    start_for_xFFastCornerDetectio_U0_empty_n;
wire   [0:0] start_for_fast_Loop_2_proc58_U0_din;
wire    start_for_fast_Loop_2_proc58_U0_full_n;
wire   [0:0] start_for_fast_Loop_2_proc58_U0_dout;
wire    start_for_fast_Loop_2_proc58_U0_empty_n;
wire    xFFastCornerDetectio_U0_start_full_n;
wire    xFFastCornerDetectio_U0_start_write;
wire    fast_Loop_2_proc58_U0_start_full_n;
wire    fast_Loop_2_proc58_U0_start_write;

fast_Loop_1_proc5765 fast_Loop_1_proc5765_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fast_Loop_1_proc5765_U0_ap_start),
    .start_full_n(fast_Loop_1_proc5765_U0_start_full_n),
    .ap_done(fast_Loop_1_proc5765_U0_ap_done),
    .ap_continue(fast_Loop_1_proc5765_U0_ap_continue),
    .ap_idle(fast_Loop_1_proc5765_U0_ap_idle),
    .ap_ready(fast_Loop_1_proc5765_U0_ap_ready),
    .start_out(fast_Loop_1_proc5765_U0_start_out),
    .start_write(fast_Loop_1_proc5765_U0_start_write),
    .p_src_mat_rows_read(p_src_mat_rows_read),
    .p_src_mat_cols_read(p_src_mat_cols_read),
    .p_src_mat_data_V_dout(p_src_mat_data_V_dout),
    .p_src_mat_data_V_empty_n(p_src_mat_data_V_empty_n),
    .p_src_mat_data_V_read(fast_Loop_1_proc5765_U0_p_src_mat_data_V_read),
    .p_src_V_V_din(fast_Loop_1_proc5765_U0_p_src_V_V_din),
    .p_src_V_V_full_n(p_src_V_V_full_n),
    .p_src_V_V_write(fast_Loop_1_proc5765_U0_p_src_V_V_write),
    .p_dst_mat_rows_read(p_dst_mat_rows_read),
    .p_dst_mat_cols_read(p_dst_mat_cols_read),
    .p_threshold(p_threshold),
    .p_src_mat_rows_read_out_din(fast_Loop_1_proc5765_U0_p_src_mat_rows_read_out_din),
    .p_src_mat_rows_read_out_full_n(p_src_mat_rows_read_c_full_n),
    .p_src_mat_rows_read_out_write(fast_Loop_1_proc5765_U0_p_src_mat_rows_read_out_write),
    .p_src_mat_cols_read_out_din(fast_Loop_1_proc5765_U0_p_src_mat_cols_read_out_din),
    .p_src_mat_cols_read_out_full_n(p_src_mat_cols_read_c_full_n),
    .p_src_mat_cols_read_out_write(fast_Loop_1_proc5765_U0_p_src_mat_cols_read_out_write),
    .p_dst_mat_rows_read_out_din(fast_Loop_1_proc5765_U0_p_dst_mat_rows_read_out_din),
    .p_dst_mat_rows_read_out_full_n(p_dst_mat_rows_read_c_full_n),
    .p_dst_mat_rows_read_out_write(fast_Loop_1_proc5765_U0_p_dst_mat_rows_read_out_write),
    .p_dst_mat_cols_read_out_din(fast_Loop_1_proc5765_U0_p_dst_mat_cols_read_out_din),
    .p_dst_mat_cols_read_out_full_n(p_dst_mat_cols_read_c_full_n),
    .p_dst_mat_cols_read_out_write(fast_Loop_1_proc5765_U0_p_dst_mat_cols_read_out_write),
    .p_threshold_out_din(fast_Loop_1_proc5765_U0_p_threshold_out_din),
    .p_threshold_out_full_n(p_threshold_c_full_n),
    .p_threshold_out_write(fast_Loop_1_proc5765_U0_p_threshold_out_write)
);

xFFastCornerDetectio xFFastCornerDetectio_U0(
    .p_strm_in_V_V_dout(p_src_V_V_dout),
    .p_strm_in_V_V_empty_n(p_src_V_V_empty_n),
    .p_strm_in_V_V_read(xFFastCornerDetectio_U0_p_strm_in_V_V_read),
    .p_strm_out_V_V_din(xFFastCornerDetectio_U0_p_strm_out_V_V_din),
    .p_strm_out_V_V_full_n(p_dst_V_V_full_n),
    .p_strm_out_V_V_write(xFFastCornerDetectio_U0_p_strm_out_V_V_write),
    .p_src_mat_rows_read_dout(p_src_mat_rows_read_c_dout),
    .p_src_mat_rows_read_empty_n(p_src_mat_rows_read_c_empty_n),
    .p_src_mat_rows_read_read(xFFastCornerDetectio_U0_p_src_mat_rows_read_read),
    .p_src_mat_cols_read_dout(p_src_mat_cols_read_c_dout),
    .p_src_mat_cols_read_empty_n(p_src_mat_cols_read_c_empty_n),
    .p_src_mat_cols_read_read(xFFastCornerDetectio_U0_p_src_mat_cols_read_read),
    .p_threshold_dout(p_threshold_c_dout),
    .p_threshold_empty_n(p_threshold_c_empty_n),
    .p_threshold_read(xFFastCornerDetectio_U0_p_threshold_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(xFFastCornerDetectio_U0_ap_done),
    .ap_start(xFFastCornerDetectio_U0_ap_start),
    .ap_ready(xFFastCornerDetectio_U0_ap_ready),
    .ap_idle(xFFastCornerDetectio_U0_ap_idle),
    .ap_continue(xFFastCornerDetectio_U0_ap_continue)
);

fast_Loop_2_proc58 fast_Loop_2_proc58_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fast_Loop_2_proc58_U0_ap_start),
    .ap_done(fast_Loop_2_proc58_U0_ap_done),
    .ap_continue(fast_Loop_2_proc58_U0_ap_continue),
    .ap_idle(fast_Loop_2_proc58_U0_ap_idle),
    .ap_ready(fast_Loop_2_proc58_U0_ap_ready),
    .p_dst_mat_rows_read_dout(p_dst_mat_rows_read_c_dout),
    .p_dst_mat_rows_read_empty_n(p_dst_mat_rows_read_c_empty_n),
    .p_dst_mat_rows_read_read(fast_Loop_2_proc58_U0_p_dst_mat_rows_read_read),
    .p_dst_mat_cols_read_dout(p_dst_mat_cols_read_c_dout),
    .p_dst_mat_cols_read_empty_n(p_dst_mat_cols_read_c_empty_n),
    .p_dst_mat_cols_read_read(fast_Loop_2_proc58_U0_p_dst_mat_cols_read_read),
    .p_dst_V_V_dout(p_dst_V_V_dout),
    .p_dst_V_V_empty_n(p_dst_V_V_empty_n),
    .p_dst_V_V_read(fast_Loop_2_proc58_U0_p_dst_V_V_read),
    .p_dst_mat_data_V_din(fast_Loop_2_proc58_U0_p_dst_mat_data_V_din),
    .p_dst_mat_data_V_full_n(p_dst_mat_data_V_full_n),
    .p_dst_mat_data_V_write(fast_Loop_2_proc58_U0_p_dst_mat_data_V_write)
);

fifo_w8_d2_A_x p_src_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_Loop_1_proc5765_U0_p_src_V_V_din),
    .if_full_n(p_src_V_V_full_n),
    .if_write(fast_Loop_1_proc5765_U0_p_src_V_V_write),
    .if_dout(p_src_V_V_dout),
    .if_empty_n(p_src_V_V_empty_n),
    .if_read(xFFastCornerDetectio_U0_p_strm_in_V_V_read)
);

fifo_w32_d2_A p_src_mat_rows_read_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_Loop_1_proc5765_U0_p_src_mat_rows_read_out_din),
    .if_full_n(p_src_mat_rows_read_c_full_n),
    .if_write(fast_Loop_1_proc5765_U0_p_src_mat_rows_read_out_write),
    .if_dout(p_src_mat_rows_read_c_dout),
    .if_empty_n(p_src_mat_rows_read_c_empty_n),
    .if_read(xFFastCornerDetectio_U0_p_src_mat_rows_read_read)
);

fifo_w32_d2_A p_src_mat_cols_read_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_Loop_1_proc5765_U0_p_src_mat_cols_read_out_din),
    .if_full_n(p_src_mat_cols_read_c_full_n),
    .if_write(fast_Loop_1_proc5765_U0_p_src_mat_cols_read_out_write),
    .if_dout(p_src_mat_cols_read_c_dout),
    .if_empty_n(p_src_mat_cols_read_c_empty_n),
    .if_read(xFFastCornerDetectio_U0_p_src_mat_cols_read_read)
);

fifo_w32_d3_A p_dst_mat_rows_read_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_Loop_1_proc5765_U0_p_dst_mat_rows_read_out_din),
    .if_full_n(p_dst_mat_rows_read_c_full_n),
    .if_write(fast_Loop_1_proc5765_U0_p_dst_mat_rows_read_out_write),
    .if_dout(p_dst_mat_rows_read_c_dout),
    .if_empty_n(p_dst_mat_rows_read_c_empty_n),
    .if_read(fast_Loop_2_proc58_U0_p_dst_mat_rows_read_read)
);

fifo_w32_d3_A p_dst_mat_cols_read_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_Loop_1_proc5765_U0_p_dst_mat_cols_read_out_din),
    .if_full_n(p_dst_mat_cols_read_c_full_n),
    .if_write(fast_Loop_1_proc5765_U0_p_dst_mat_cols_read_out_write),
    .if_dout(p_dst_mat_cols_read_c_dout),
    .if_empty_n(p_dst_mat_cols_read_c_empty_n),
    .if_read(fast_Loop_2_proc58_U0_p_dst_mat_cols_read_read)
);

fifo_w8_d2_A_x p_threshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_Loop_1_proc5765_U0_p_threshold_out_din),
    .if_full_n(p_threshold_c_full_n),
    .if_write(fast_Loop_1_proc5765_U0_p_threshold_out_write),
    .if_dout(p_threshold_c_dout),
    .if_empty_n(p_threshold_c_empty_n),
    .if_read(xFFastCornerDetectio_U0_p_threshold_read)
);

fifo_w8_d2_A_x p_dst_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFFastCornerDetectio_U0_p_strm_out_V_V_din),
    .if_full_n(p_dst_V_V_full_n),
    .if_write(xFFastCornerDetectio_U0_p_strm_out_V_V_write),
    .if_dout(p_dst_V_V_dout),
    .if_empty_n(p_dst_V_V_empty_n),
    .if_read(fast_Loop_2_proc58_U0_p_dst_V_V_read)
);

start_for_xFFastCg8j start_for_xFFastCg8j_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFFastCornerDetectio_U0_din),
    .if_full_n(start_for_xFFastCornerDetectio_U0_full_n),
    .if_write(fast_Loop_1_proc5765_U0_start_write),
    .if_dout(start_for_xFFastCornerDetectio_U0_dout),
    .if_empty_n(start_for_xFFastCornerDetectio_U0_empty_n),
    .if_read(xFFastCornerDetectio_U0_ap_ready)
);

start_for_fast_Lohbi start_for_fast_Lohbi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fast_Loop_2_proc58_U0_din),
    .if_full_n(start_for_fast_Loop_2_proc58_U0_full_n),
    .if_write(fast_Loop_1_proc5765_U0_start_write),
    .if_dout(start_for_fast_Loop_2_proc58_U0_dout),
    .if_empty_n(start_for_fast_Loop_2_proc58_U0_empty_n),
    .if_read(fast_Loop_2_proc58_U0_ap_ready)
);

assign ap_done = fast_Loop_2_proc58_U0_ap_done;

assign ap_idle = (xFFastCornerDetectio_U0_ap_idle & fast_Loop_2_proc58_U0_ap_idle & fast_Loop_1_proc5765_U0_ap_idle);

assign ap_ready = fast_Loop_1_proc5765_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = fast_Loop_2_proc58_U0_ap_done;

assign ap_sync_ready = fast_Loop_1_proc5765_U0_ap_ready;

assign fast_Loop_1_proc5765_U0_ap_continue = 1'b1;

assign fast_Loop_1_proc5765_U0_ap_start = ap_start;

assign fast_Loop_1_proc5765_U0_start_full_n = (start_for_xFFastCornerDetectio_U0_full_n & start_for_fast_Loop_2_proc58_U0_full_n);

assign fast_Loop_2_proc58_U0_ap_continue = ap_continue;

assign fast_Loop_2_proc58_U0_ap_start = start_for_fast_Loop_2_proc58_U0_empty_n;

assign fast_Loop_2_proc58_U0_start_full_n = 1'b1;

assign fast_Loop_2_proc58_U0_start_write = 1'b0;

assign p_dst_mat_data_V_din = fast_Loop_2_proc58_U0_p_dst_mat_data_V_din;

assign p_dst_mat_data_V_write = fast_Loop_2_proc58_U0_p_dst_mat_data_V_write;

assign p_src_mat_data_V_read = fast_Loop_1_proc5765_U0_p_src_mat_data_V_read;

assign start_for_fast_Loop_2_proc58_U0_din = 1'b1;

assign start_for_xFFastCornerDetectio_U0_din = 1'b1;

assign xFFastCornerDetectio_U0_ap_continue = 1'b1;

assign xFFastCornerDetectio_U0_ap_start = start_for_xFFastCornerDetectio_U0_empty_n;

assign xFFastCornerDetectio_U0_start_full_n = 1'b1;

assign xFFastCornerDetectio_U0_start_write = 1'b0;

endmodule //fast
